services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    ports:
      - "5053:53/udp"
      - "5053:53/tcp"
    volumes:
      - ./unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
      - ./unbound-data:/opt/unbound/etc/unbound
    restart: unless-stopped
